include: package:lints/core.yaml, package:lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude: [build/**, .dart_tool/**, .packages, .flutter-plugins, .flutter-plugins-dependencies, lib/firebase_options.dart]
  errors:
    unused_local_variable: error
    unused_element: info
    unused_field: info

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_locals
    - avoid_unused_constructor_parameters
    - prefer_void_to_null
    - avoid_classes_with_only_static_members
    - prefer_equal_for_default_values
    - prefer_single_quotes
    - type_annotate_public_apis
    - use_key_in_widget_constructors
    - sort_pub_dependencies: false