name: studiconnect
description: Eine App, um Lerngruppen zu finden.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  curved_navigation_bar: ^1.0.3
  cupertino_icons: ^1.0.2
  oktoast: ^3.4.0

  logger: ^2.0.2+1
  yaml: ^3.1.2
  url_launcher: ^6.2.1
  intl: ^0.18.1

  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  firebase_crashlytics: ^3.4.9
  google_sign_in: ^6.1.6
  google_fonts: ^5.1.0
  auth_buttons: ^3.0.2

  redux: ^5.0.0
  flutter_redux: ^0.10.0
  graphql: ^5.1.3
  http: ^1.1.0
  connectivity_plus: ^5.0.2
  web_socket_channel: ^2.4.0

  flutter_map: ^6.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  latlong2: ^0.9.0
  location: ^5.0.3

  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  image_picker: ^1.0.5
  share_plus: ^7.2.1
  flutter_native_splash: ^2.3.9

dev_dependencies:
  flutter_lints: ^3.0.0
  dartdoc: ^6.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon.png
    - pubspec.yaml
